### ISSUE TITLE
Not supported dict %s" % hex(self.header.type)) AttributeError: Header instance has no attribute 'type'

### ISSUE THREAD

**Issue by stroobandt** [sv99/lsdreader#1]
```
Unpacking Dict...
Header:
    Magic:             LingVo
    Name:              OxfordHachetteConcise (Fr-En)
    Version:           0x131001
    Entries:           28433
    Source language:   1036 French
    Target language:   1033 English
    Icon enable:       True
    First heading:     _Communication mode d’emploi
    Last heading:      zygomatique
    Capitals:          _‘ABCDEFGHIJKLMNOPQRSTUVWXYZ
    Checksume:         0x2aedb9
    Pages count:       394
    AnnotationOffset:  0x405
    DictionaryEncoderOffset: 0xe0f
    ArticlesOffset:    0x91a6
    Pages start:       0x27d9b9
    Pages end:         0x2aedbd
    Overlay data:      0xa128c089
Traceback (most recent call last):
  File "/usr/local/bin/lsdreader", line 9, in <module>
    load_entry_point('lingvoreader==0.1.4', 'console_scripts', 'lsdreader')()
  File "/usr/local/lib/python2.7/dist-packages/lingvoreader/lsdreader.py", line 411, in main
    unpack(d, args.outdir, args.verbose)
  File "/usr/local/lib/python2.7/dist-packages/lingvoreader/lsdreader.py", line 343, in unpack
    m = LsdFile(dict_file)
  File "/usr/local/lib/python2.7/dist-packages/lingvoreader/lsdreader.py", line 195, in __init__
    raise LsdError("Not supported dict %s" % hex(self.header.type))
AttributeError: Header instance has no attribute 'type'
```

**Comment by sv99** [comment]
send me dict please

**Comment by superkeyor** [comment]
is this solved? I came across the same issue

**Comment by sv99** [comment]
send me dict sv99@inbox.ru

**Comment by stroobandt** [comment]
With version 0.1.5 of `lsdreader`, the final error is now:
`Not supported dict version 0x131001`

```
$ lsdreader -i OxfordHachetteConciseFrEn.lsd -o ../dsl/

Unpacking Dict...
Header:
    Magic:             LingVo
    Name:              OxfordHachetteConcise (Fr-En)
    Version:           0x131001
    Entries:           28433
    Source language:   1036 French
    Target language:   1033 English
    Icon enable:       True
    First heading:     _Communication mode d’emploi
    Last heading:      zygomatique
    Capitals:          _‘ABCDEFGHIJKLMNOPQRSTUVWXYZ
    Checksume:         0x2aedb9
    Pages count:       394
    AnnotationOffset:  0x405
    DictionaryEncoderOffset: 0xe0f
    ArticlesOffset:    0x91a6
    Pages start:       0x27d9b9
    Pages end:         0x2aedbd
    Overlay data:      0xa128c089
Traceback (most recent call last):
  File "/usr/local/bin/lsdreader", line 9, in <module>
    load_entry_point('lingvoreader==0.1.5', 'console_scripts', 'lsdreader')()
  File "/usr/local/lib/python2.7/dist-packages/lingvoreader/lsdreader.py", line 411, in main
    unpack(d, args.outdir, args.verbose)
  File "/usr/local/lib/python2.7/dist-packages/lingvoreader/lsdreader.py", line 343, in unpack
    m = LsdFile(dict_file)
  File "/usr/local/lib/python2.7/dist-packages/lingvoreader/lsdreader.py", line 195, in __init__
    raise LsdError("Not supported dict version %s" % hex(self.header.version))
lingvoreader.lsdreader.LsdError: Not supported dict version 0x131001
```

**Comment by stroobandt** [comment]
@sv99 Have you received the dictionary files?

**Comment by sv99** [comment]
new version support you dict version.
