### ISSUE TITLE
I get an error.

### ISSUE THREAD

**Issue by isemsez** [sv99/lsdreader#10]
Hi.
C:\Users\Malay>lsdreader -h
Traceback (most recent call last):
  File "C:\Users\Malay\AppData\Local\Programs\Python\Python35-32\Scripts\lsdreader-script.py", line 11, in <module>
    load_entry_point('lingvoreader==0.2.8', 'console_scripts', 'lsdreader')()
  File "c:\users\malay\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\malay\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\malay\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\malay\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\malay\appdata\local\programs\python\python35-32\lib\site-packages\lingvoreader\lsdreader.py", line 53
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

**Comment by balta2ar** [comment]
I suppose this script is for Python2, and you're running it using Python3.

**Comment by isemsez** [comment]
Would appreciate if somebody help with converting one .lsd file.

I run an Authohotkey scripting language project and have integrated a Python3 based nltk utility (with difficulty). As I don't much understand in Python, I'm reluctant to experiment with Python2 in order not to ruin what I've already set.

**Comment by sv99** [comment]
Send me you lsd sv99@inbox.ru

**Comment by isemsez** [comment]
Thank you.
It helped me with derived words.
