### ISSUE TITLE
This isn't compatible with python 3

### ISSUE THREAD

**Issue by A-Shahbazi** [sv99/lsdreader#11]

**Comment by A-Shahbazi** [comment]
```Traceback (most recent call last):
  File "/home/ali/.local/bin/lsdreader", line 11, in <module>
    load_entry_point('lingvoreader', 'console_scripts', 'lsdreader')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ali/pyglossary-master/lsdreader/lingvoreader/lsdreader.py", line 53
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

**Comment by sv99** [comment]
New release 0.2.12 support python 3

**Comment by A-Shahbazi** [comment]
I can confirm this is now working with python3
Thank you @sv99
