### ISSUE TITLE
I can't run a program

### ISSUE THREAD

**Issue by dumpty-0-humpty** [sv99/lsdreader#6]
Hi, I've got a problem by starting lsdreader.

```
$ lsdreader -v
Traceback (most recent call last):
  File "/usr/local/bin/lsdreader", line 7, in <module>
    from lingvoreader.lsdreader import main
  File "/usr/local/lib/python3.6/site-packages/lingvoreader/lsdreader.py", line 53
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

**Comment by dumpty-0-humpty** [comment]
> python3.6

And I know now why.

Thanks for great program :)
