### ISSUE TITLE
instructions for new user

### ISSUE THREAD

**Issue by TeomanCrtgl** [sv99/lsdreader#7]
Hi, thanks for this code. 

I installed it in Windows. I have lsd file. How could I convert it with your code. Could you explain step by step, please?

**Comment by sv99** [comment]
`pip install lingvoreader` install script `lsdreader`

in the cmd window:
```
lsdreader -h
lsdreader --header -i xxx.lsd
lsdreader -i xxx.lsd
```
make xxx.dsl

**Comment by TeomanCrtgl** [comment]
thanks for answer but I couldn't do it and took this error.

C:\Users\xxxx\Downloads\lsdreader-master>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install lingvoreader
  File "<stdin>", line 1
    pip install lingvoreader
              ^
SyntaxError: invalid syntax
>>>

**Comment by balta2ar** [comment]
These are commands to run in the console (bash, zsh, etc..) not in the Python shell.

**Comment by sv99** [comment]
Download not need.
pip - package manager for python.
in the windows command shell (cmd):
```
pip install lingvoreader
lsdreader -h
```
lsdreader - python command script for windows shell, don`t run python shell

**Comment by TeomanCrtgl** [comment]
Thanks for your answers. I tried it many times with windows cmd but I received an error:

C:\Users\Teoman\Desktop\lsdreader-0.2.8>**pip install lingvoreader**
'pip' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\Teoman\Desktop\lsdreader-0.2.8>

I have the Python 2.7 and 3.4 in my PC. Normally these versions contain "pip". I can not be success with Windows CMD and Python Shell when I try to insert the code " pip install lingvoreader".

**I could be success like that in Windows CMD:**

C:\Users\Teoman\Desktop\lsdreader-0.2.8>**python setup.py install**
running install
running bdist_egg
running egg_info
creating lingvoreader.egg-info
writing lingvoreader.egg-info\PKG-INFO
writing top-level names to lingvoreader.egg-info\top_level.txt
writing dependency_links to lingvoreader.egg-info\dependency_links.txt
writing entry points to lingvoreader.egg-info\entry_points.txt
writing manifest file 'lingvoreader.egg-info\SOURCES.txt'
reading manifest file 'lingvoreader.egg-info\SOURCES.txt'
writing manifest file 'lingvoreader.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\lingvoreader
.
.
.
.


Where I am making mistake?

**Comment by sv99** [comment]
which python distro used?

**Comment by TeomanCrtgl** [comment]
Python 2.7 and 3.4

**Comment by sv99** [comment]
which distribution? How you install python?

**Comment by sv99** [comment]
If you have single lsd send me link to this file. I convert this file for you.

**Comment by TeomanCrtgl** [comment]
Thanks for your kindness. I have to learn to use your script because I want to help to my friend for creating Russian Turkish dictionary. Also I am trying to create my own French English dictionary. So I have to learn to use your script.

I installed the python from official web site to use pyglossary by illus.

**Comment by sv99** [comment]
Official distribution install 2.7 in the c:/Python27
pip and scripts in the folder c:\Python27\Scripts - this folder must be in the %PATH%

```
cmd>echo %PATH%
cmd>set PATH=C:\Python27;C:\Python27\Scripts;%PATH%
cmd>echo %PATH%
cmd>pip --version
cmd>pip install lingvoreader
cmd>lsdreader --version 
```

**Comment by TeomanCrtgl** [comment]
It works! Thanks a lot!

Now Its time to convert .dsl file to csv and other formats.

But pyglossary doesn't convert my .dsl (.lsd to .dsl)

**Comment by TeomanCrtgl** [comment]
C:\>lsdreader --header -i rutr.lsd
Unpacking dict: rutr.lsd
Traceback (most recent call last):
  File "C:\Python27\Scripts\lsdreader-script.py", line 11, in <module>
    load_entry_point('lingvoreader==0.2.8', 'console_scripts', 'lsdreader')()
  File "build\bdist.win32\egg\lingvoreader\lsdreader.py", line 136, in main
  File "build\bdist.win32\egg\lingvoreader\lsdreader.py", line 75, in header
  File "build\bdist.win32\egg\lingvoreader\lsdfile.py", line 121, in __init__
IOError: [Errno 2] No such file or directory: 'rutr.lsd'

**Comment by sv99** [comment]
try full path

**Comment by TeomanCrtgl** [comment]
Thanks sv99 for your helping, I converted my file to .dsl successfully, I have some questions;
How could I take output with UTF-8 
Is there a way to convert .dsl file to mobi or other formats?

**Comment by sith-on-mars** [comment]
Hi @sv99 . I was trying to covert two dictionaries to from lsd to dsl format. I've finished the installation of lsdreader, but I'm stuck at the file conversion. I've tried it for many hours but no help. I'm really bad at programming because I'm totally new. 

Could you convert two files for me, please?

**Comment by haoshu1995** [comment]
Why do I encounter 
TypeError: write() argument must be str, not bytes
when I run this program, please?

**Comment by sv99** [comment]
> Why do I encounter TypeError: write() argument must be str, not bytes when I run this program, please?

 OS, python version?

**Comment by haoshu1995** [comment]
> > Why do I encounter TypeError: write() argument must be str, not bytes when I run this program, please?
> 
> OS, python version?

Python 3.12. What version does this program require?

**Comment by sv99** [comment]
> Python 3.12. What version does this program require?
Windows? Full command and replay please.

**Comment by sv99** [comment]
> Python 3.12. What version does this program require?

Just checked on the my Mac. On Windows may check today.

**Comment by Musrar** [comment]
Hello, I'm on Windows 10 and python 3.13.14 and after installing lingvoreader with pip and trying to run it I got these errors:

`lsdreader -i .\ukreng.lsd
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Scripts\lsdreader.exe\__main__.py", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\lingvoreader\lsdreader.py", line 147, in main
    unpack(dicts, args.outdir, args.verbose)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\lingvoreader\lsdreader.py", line 45, in
 unpack
    print("Unpacking dict: %s" % dicts[0])
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 381, in write
TypeError: write() argument must be str, not bytes`



I can't edit lsdreader.exe, and I couldn't see how to fix the errors in lsdreader.py
